# Generated by Django 2.1 on 2018-08-27 02:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('EmployeeCard', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_DealDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Amount', models.IntegerField(default=0)),
                ('Qty', models.IntegerField(default=0)),
                ('TotalAmount', models.IntegerField(default=0)),
                ('Remark', models.CharField(max_length=100, null=True)),
                ('CreateDate', models.DateTimeField(auto_now=True)),
                ('EditDate', models.DateTimeField(auto_now=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='M_DealMaster',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDate', models.DateTimeField()),
                ('Status', models.CharField(choices=[('0', '作廢')], max_length=10, null=True)),
                ('Amount', models.IntegerField(default=0)),
                ('PayType', models.CharField(choices=[('PT01', '現金'), ('PT02', '悠遊卡')], max_length=10)),
                ('IsCheckout', models.BooleanField()),
                ('IsOutside', models.BooleanField()),
                ('CreateDate', models.DateTimeField(auto_now=True)),
                ('EditDate', models.DateTimeField(auto_now=True, null=True)),
                ('Cashier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='EmployeeCard.M_EmployeeCard')),
                ('Creator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='CreatorMaster', to=settings.AUTH_USER_MODEL)),
                ('Editor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='EditorMaster', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
