# Generated by Django 2.1 on 2018-09-10 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0002_m_dealmaster_lotno'),
    ]

    sql = """
        CREATE VIEW "Deal_M_V_DealDetail" AS
         SELECT
            ROW_NUMBER() OVER (ORDER BY M."DealDate") AS id
            ,M."DealDate"
            ,M."Status"
            ,M."Amount"
            ,M."PayType"
            ,M."IsCheckout"
            ,M."IsOutside"
            ,D."Amount" AS DetailAmount
            ,D."Qty"
            ,D."TotalAmount" AS DetailTotalAmount
            ,D."Remark" AS DetailRemark
            ,D."MasterID_id"
            ,F."FeeID"
            ,F."FeeName"
            ,F."FeeAmount"
            ,F."Remark" AS FeeRemark
            ,F."FeeType"
            ,I."InvoiceNo"
            FROM "Deal_m_dealdetail" D
            INNER JOIN "Deal_m_dealmaster" M ON D."MasterID_id"=M."id"
            INNER JOIN "FeeItem_m_feeitem" F ON D."FeeID_id"=F."id"
            INNER JOIN "Invoice_m_invoice" I ON M."InvoiceNo_id"=I."id"

    """

    operations = [
        migrations.RunSQL("""drop view if exists "Deal_M_V_DealDetail";"""),
        migrations.RunSQL(sql),
    ]
