# Generated by Django 2.1 on 2018-09-10 01:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Term', '0001_initial'),
        ('Penalty', '0001_initial'),
        ('Deal', '0002_m_dealmaster_lotno'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_dealdetail',
            name='PenaltyID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Penalty.M_Penalty'),
        ),
        migrations.AddField(
            model_name='m_dealdetail',
            name='TermID',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='Term.M_Term'),
        ),
        migrations.AlterField(
            model_name='m_dealmaster',
            name='Status',
            field=models.CharField(choices=[('0', '作廢'), ('1', '正常')], max_length=10, null=True),
        ),
    ]
