# Generated by Django 2.1 on 2018-10-23 01:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Deal', '0004_m_v_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_V_DealDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDate', models.DateTimeField()),
                ('Status', models.CharField(choices=[('0', '作廢'), ('1', '正常')], max_length=10, null=True)),
                ('Amount', models.IntegerField(null=True)),
                ('PayType', models.CharField(choices=[('PT01', '現金'), ('PT02', '悠遊卡')], max_length=10, null=True)),
                ('IsCheckout', models.BooleanField()),
                ('IsOutside', models.BooleanField()),
                ('DetailAmount', models.IntegerField(null=True)),
                ('Qty', models.IntegerField(null=True)),
                ('DetailTotalAmount', models.IntegerField(null=True)),
                ('DetailRemark', models.CharField(max_length=100, null=True)),
                ('MasterID_id', models.IntegerField(null=True)),
                ('FeeID', models.CharField(max_length=10, null=True)),
                ('FeeName', models.CharField(max_length=50, null=True)),
                ('FeeAmount', models.IntegerField(null=True)),
                ('FeeRemark', models.CharField(max_length=100, null=True)),
                ('FeeType', models.CharField(choices=[('FY01', '資料使用費'), ('FY02', '服務費'), ('FY03', '證照費'), ('FY04', '登記費'), ('FY05', '規費'), ('FY06', '罰緩'), ('FY07', '考試報名費'), ('FY08', '其他')], max_length=10, null=True)),
                ('InvoiceNo', models.CharField(max_length=20, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='m_dealmaster',
            name='Cashier',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
    ]
