# Generated by Django 2.1 on 2018-08-31 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_Station',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StationID', models.CharField(max_length=10, unique=True)),
                ('StationName', models.CharField(max_length=50)),
                ('EditDate', models.DateTimeField(auto_now=True)),
                ('Editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='M_Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('StoreID', models.CharField(max_length=10, unique=True)),
                ('StoreName', models.CharField(max_length=50)),
                ('EditDate', models.DateTimeField(auto_now=True)),
                ('Editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='m_station',
            name='StoreID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='Store.M_Store'),
        ),
    ]
