# Generated by Django 2.1 on 2018-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    sql = """
        create VIEW "Store_M_V_Station" as
            SELECT
              a."id",
              a."StationID",
              a."StationName",
              b."StoreID",
              b."StoreName"
            FROM
              "Store_m_station" as a,
              "Store_m_store" as b
            WHERE
              a."StoreID_id" = b."id"
    """


    operations = [
        migrations.RunSQL("drop view if exists Store_M_V_Station;"),
        migrations.RunSQL(sql),
        migrations.CreateModel(
            name='M_V_Station',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('StationID', models.CharField(max_length=10, unique=True)),
                ('StationName', models.CharField(max_length=50)),
                ('StoreID', models.CharField(max_length=10, unique=True)),
                ('StoreName', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'Store_M_V_Station',
                'managed': False,
            },
        ),
    ]
