# Generated by Django 2.1 on 2018-09-10 01:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ExportExcel', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_V_DayReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDate', models.DateField()),
                ('Status', models.CharField(choices=[('0', '作廢'), ('1', '正常')], max_length=10)),
                ('PayType', models.CharField(choices=[('PT01', '現金'), ('PT02', '悠遊卡')], max_length=10)),
                ('FeeID_id', models.IntegerField()),
                ('FeeID', models.CharField(max_length=10)),
                ('FeeName', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('RowCount', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'ExportExcel_M_V_DayReport',
            },
        ),
        migrations.CreateModel(
            name='M_V_MonthReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDateYear', models.IntegerField()),
                ('DealDateMonth', models.IntegerField()),
                ('Status', models.CharField(choices=[('0', '作廢'), ('1', '正常')], max_length=10)),
                ('PayType', models.CharField(choices=[('PT01', '現金'), ('PT02', '悠遊卡')], max_length=10)),
                ('FeeID_id', models.IntegerField()),
                ('FeeID', models.CharField(max_length=10)),
                ('FeeName', models.CharField(max_length=50)),
                ('Amount', models.IntegerField()),
                ('RowCount', models.IntegerField()),
            ],
            options={
                'managed': False,
                'db_table': 'ExportExcel_M_V_MonthReport',
            },
        ),
    ]
