# Generated by Django 2.1 on 2018-08-10 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ExportExcel', '0002_m_v_dayreport_m_v_monthreport'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_V_FeeItemReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDate', models.DateTimeField()),
                ('StationID', models.CharField(max_length=10)),
                ('InvoiceNo', models.CharField(max_length=20)),
                ('PayType', models.CharField(choices=[('PT01', '現金'), ('PT02', '悠遊卡')], max_length=10)),
                ('Status', models.CharField(choices=[('0', '作廢'), ('1', '正常')], max_length=10)),
                ('FeeID', models.CharField(max_length=10)),
                ('FeeName', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('Amount', models.IntegerField()),
                ('Remark', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ExportExcel_M_V_FeeItemReport',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='M_V_PenaltyReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DealDate', models.DateTimeField()),
                ('PenaltyID', models.CharField(max_length=10)),
                ('PenaltyName', models.CharField(max_length=50)),
                ('TermID', models.CharField(max_length=10)),
                ('TermName', models.CharField(max_length=50)),
                ('Qty', models.IntegerField()),
                ('TotalAmount', models.IntegerField()),
                ('Remark', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'ExportExcel_M_V_PenaltyReport',
                'managed': False,
            },
        ),
    ]
