# Generated by Django 2.1 on 2018-09-18 21:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ExportExcel', '0003_m_v_feeitemreport_m_v_penaltyreport'),
    ]

    sqlDayReport = """
        CREATE VIEW "ExportExcel_M_V_DayReport" AS
         SELECT
            row_number() OVER (ORDER BY M."DealDate"::date) AS id
            ,M."DealDate"::date
            ,M."Status"
            ,M."PayType"
            ,D."FeeID_id"
            ,F."FeeID"
            ,F."FeeName"
            ,SUM(D."TotalAmount") AS "Amount"
            ,COUNT(*) AS "RowCount"
            ,M."IsOutside"
            FROM "Deal_m_dealdetail" D
            INNER JOIN "Deal_m_dealmaster" M ON D."MasterID_id"=M.id
            INNER JOIN "FeeItem_m_feeitem" F ON D."FeeID_id"=F.id
            WHERE M."IsCheckout"=True
            GROUP BY M."DealDate"::date,M."Status",M."PayType",D."FeeID_id",F."FeeID",F."FeeName",M."IsOutside"
    """
    sqlMonthReport = """
        CREATE VIEW "ExportExcel_M_V_MonthReport" AS
         SELECT
            row_number() OVER (ORDER BY D."FeeID_id") AS id
            ,EXTRACT(YEAR FROM M."DealDate") AS "DealDateYear"
            ,EXTRACT(MONTH FROM M."DealDate") AS "DealDateMonth"
            ,M."Status"
            ,M."PayType"
            ,D."FeeID_id"
            ,F."FeeID"
            ,F."FeeName"
            ,SUM(D."TotalAmount") AS "Amount"
            ,COUNT(*) AS "RowCount"
            ,M."IsOutside"
            FROM "Deal_m_dealdetail" D
            INNER JOIN "Deal_m_dealmaster" M ON D."MasterID_id"=M.id
            INNER JOIN "FeeItem_m_feeitem" F ON D."FeeID_id"=F.id
            WHERE M."IsCheckout"=True
            GROUP BY EXTRACT(MONTH FROM M."DealDate"),EXTRACT(YEAR FROM M."DealDate"),M."Status",M."PayType",D."FeeID_id",F."FeeID",F."FeeName",M."IsOutside"
    """

    operations = [
        migrations.RunSQL("""drop view if exists "ExportExcel_M_V_DayReport";"""),
        migrations.RunSQL(sqlDayReport),
        migrations.RunSQL("""drop view if exists "ExportExcel_M_V_MonthReport";"""),
        migrations.RunSQL(sqlMonthReport),
    ]
