# Generated by Django 2.1.3 on 2018-11-30 02:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_PrintData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('EnableDate', models.DateTimeField()),
                ('Salesman', models.CharField(max_length=50)),
                ('Accounting', models.CharField(max_length=50)),
                ('Chief', models.CharField(max_length=50)),
                ('Tel', models.CharField(max_length=50)),
                ('Fax', models.CharField(max_length=50)),
                ('EditDate', models.DateTimeField(auto_now=True)),
                ('Editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
