# Generated by Django 2.1 on 2018-07-22 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='M_Menu',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MenuName', models.CharField(max_length=100)),
                ('MenuLink', models.CharField(max_length=100)),
                ('MenuType', models.CharField(choices=[('MT01', '功能選項'), ('MT01', '連結選項')], max_length=10)),
                ('MenuParent', models.BigIntegerField()),
                ('MenuIcon', models.CharField(max_length=50)),
                ('IsActive', models.BooleanField()),
            ],
        ),
    ]
