# Generated by Django 2.1 on 2018-07-22 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Menu', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_menu',
            name='MenuIcon',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='m_menu',
            name='MenuLink',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='m_menu',
            name='MenuParent',
            field=models.BigIntegerField(null=True),
        ),
    ]
