# Generated by Django 2.1 on 2018-08-31 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0002_auto_20180831_0016'),
    ]

    operations = [
        migrations.CreateModel(
            name='M_V_Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('InvoiceNo', models.CharField(max_length=20)),
            ],
            options={
                'managed': False,
                'db_table': 'Invoice_M_V_Invoice',
            },
        ),
    ]
