# Generated by Django 2.1 on 2018-09-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20180915_1051'),
        ('Invoice', '0003_m_v_invoice'),
    ]

    operations = [
        migrations.AddField(
            model_name='m_invoice',
            name='StationID',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.PROTECT, to='Store.M_Station'),
            preserve_default=False,
        ),
    ]
