# Generated by Django 2.1 on 2018-09-01 20:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_auto_20180915_1051'),
        ('Invoice', '0003_m_v_invoice'),
        ('Invoice', '0004_m_invoice_stationid'),
    ]

    sql = """
        CREATE VIEW "Invoice_M_V_Invoice" AS
         SELECT max(i."InvoiceNo"::text) AS "MaxInvoice",
            min(i."InvoiceNo"::text) AS "MinInvoice",
            count(*) AS "TotalInvoice",
            sum(f."FeeAmount") AS "TotalAmount",
            i."Status",
            s."StationID",
            s."StationName",
            f."FeeID",
            f."FeeName",
            row_number() OVER (ORDER BY s."StationID") AS id
           FROM "Invoice_m_invoice" i
             JOIN "Store_m_station" s ON i."StationID_id" = s.id
             JOIN "FeeItem_m_feeitem" f ON i."FeeID_id" = f.id
          GROUP BY i."Status", s."StationID", s."StationName", f."FeeID", f."FeeName"
    """

    operations = [
        migrations.RunSQL("""drop view if exists "Invoice_M_V_Invoice";"""),
        migrations.RunSQL(sql),
    ]
