# Generated by Django 2.1 on 2018-09-02 21:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Invoice', '0005_m_v_invoice'),
    ]

    sql = """
        CREATE VIEW "Invoice_M_V_Invoice" AS
         SELECT max(i."InvoiceNo"::text) AS "MaxInvoice",
            min(i."InvoiceNo"::text) AS "MinInvoice",
            count(*) AS "TotalInvoice",
            sum(f."FeeAmount") AS "TotalAmount",
            i."Status",
            s."StationID",
            s."StationName",
            f."FeeID",
            f."FeeName",
            i."LotNo",
            row_number() OVER (ORDER BY s."StationID") AS id
           FROM "Invoice_m_invoice" i
             JOIN "Store_m_station" s ON i."StationID_id" = s.id
             JOIN "FeeItem_m_feeitem" f ON i."FeeID_id" = f.id
          GROUP BY i."Status", s."StationID", s."StationName", f."FeeID", f."FeeName",i."LotNo"
    """

    operations = [
        migrations.AddField(
            model_name='m_invoice',
            name='LotNo',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.RunSQL("""drop view if exists "Invoice_M_V_Invoice";"""),
        migrations.RunSQL(sql),
    ]
