# Generated by Django 2.1 on 2018-08-31 00:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='M_FeeItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeeID', models.CharField(max_length=10, unique=True)),
                ('FeeName', models.CharField(max_length=50)),
                ('FeeAmount', models.IntegerField(default=0)),
                ('Remark', models.CharField(max_length=100, null=True)),
                ('FeeType', models.CharField(choices=[('FY01', '資料使用費'), ('FY02', '服務費'), ('FY03', '證照費'), ('FY04', '登記費'), ('FY05', '規費'), ('FY06', '罰緩'), ('FY07', '考試報名費'), ('FY08', '其他')], max_length=10)),
                ('Status', models.CharField(choices=[('0', '停用'), ('1', '啟用')], max_length=10)),
                ('EditDate', models.DateTimeField(auto_now=True)),
                ('Editor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
