# Generated by Django 2.1.3 on 2018-11-30 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FeeItem', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='m_feeitem',
            name='FeeType',
            field=models.CharField(choices=[('FY01', '資料使用費'), ('FY04', '登記費'), ('FY03', '證照費'), ('FY02', '服務費'), ('FY05', '規費'), ('FY06', '罰緩'), ('FY07', '考試報名費'), ('FY08', '其他')], max_length=10),
        ),
    ]
